ATP_INFO = {
    "ATP": [
        {
            "name": "ADENOSINE-5'-TRIPHOSPHATE",
            "released": "true",
            "superseded_by": "null",
            "formula": "C10 H16 N5 O13 P3",
            "inchi": "InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1",
            "inchi_key": "ZKHQWZAMYRWXGA-KQYNXXCUSA-N",
            "smiles": "c1nc(c2c(n1)n(cn2)C3C(C(C(O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O)N",
            "ww_pdb_info": {
                "defined_at": "1999-07-08 00:00:00",
                "modified": "2011-06-04 00:00:00",
                "modification_flag": "N",
                "polymer_type": "NON-POLYMER",
                "standard_parent": "null"
            },
            "functional_annotations": [],
            "cross_links": [
                {"resource": "BRENDA", "resource_id": "12415"},
                {"resource": "BRENDA", "resource_id": "96166"},
                {"resource": "MetaboLights", "resource_id": "MTBLC15422"},
                {"resource": "BRENDA", "resource_id": "92425"},
                {"resource": "BindingDb", "resource_id": "50366480"},
                {"resource": "BRENDA", "resource_id": "3789"},
                {"resource": "BRENDA", "resource_id": "4"},
                {"resource": "BRENDA", "resource_id": "96167"},
                {"resource": "Guide to Pharmacology", "resource_id": "1713"},
                {"resource": "KEGG LIGAND", "resource_id": "C00002"},
                {"resource": "ZINC", "resource_id": "ZINC000004261765"},
                {"resource": "BRENDA", "resource_id": "72085"},
                {"resource": "BRENDA", "resource_id": "90940"},
                {"resource": "BRENDA", "resource_id": "91792"},
                {"resource": "BRENDA", "resource_id": "23575"},
                {"resource": "BRENDA", "resource_id": "90970"},
                {"resource": "ChEMBL", "resource_id": "CHEMBL14249"},
                {"resource": "BRENDA", "resource_id": "21348"},
                {"resource": "PubChem", "resource_id": "5957"},
                {"resource": "BRENDA", "resource_id": "4781"},
                {"resource": "DrugBank", "resource_id": "DB00171"},
                {"resource": "ChEBI", "resource_id": "15422"}
            ],
            "synonyms": [
                {"origin": "DrugBank", "value": "Striadyne"},
                {"origin": "DrugBank", "value": "Atriphos"},
                {"origin": "DrugBank", "value": "ATP"},
                {"origin": "DrugBank", "value": "Adenosine-5'-triphosphate"},
                {"origin": "DrugBank", "value": "Adenosine triphosphate"},
                {"origin": "DrugBank", "value": "Adenosine 5'-triphosphate"},
            ],
            "phys_chem_properties": {
                "crippen_mr":92.446,
                "num_atom_stereo_centers":6,
                "crippen_clog_p":-2.438,
                "num_rings":3,
                "num_rotatable_bonds":15,
                "num_heteroatoms":21,
                "fraction_csp3":0.5,
                "num_aromatic_rings":2,
                "exactmw":506.996,
                "num_spiro_atoms":0,
                "num_heavy_atoms":31,
                "num_aliphatic_rings":1,
                "num_hbd":7,
                "num_saturated_heterocycles":1,
                "tpsa":279.13,
                "num_bridgehead_atoms":0,
                "num_aromatic_heterocycles":2,
                "labute_asa":194.334,
                "num_hba":18,
                "num_amide_bonds":0,
                "num_saturated_rings":1,
                "lipinski_hba":18.0,
                "num_unspec_atom_stereo_centers":0,
                "lipinski_hbd":8.0,
                "num_heterocycles":3,
                "num_aliphatic_heterocycles":1,
            }
        }
    ]
}